FROM node:20-bookworm-slim

WORKDIR /app

COPY package.json ./
RUN npm install --ignore-scripts --loglevel=info --no-audit --no-fund

COPY . .
RUN mkdir -p public/uploads

EXPOSE 1337

CMD ["npm", "run", "develop"]
